import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import QueryProvider from "@/components/QueryProvider";
import TaskStat from "@/components/taskStat";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen overflow-hidden`}
      >
        <QueryProvider>
          <div className="h-full grid overflow-hidden grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-4 p-4 grid-rows-12">
            <div className="col-span-1 sm:col-span-2 md:col-span-3 lg:col-span-4 xl:col-span-5 row-span-2 row-start-1 bg-gray-200 rounded-lg shadow-md p-4">
              <TaskStat />
            </div>
            <div className="col-span-1 row-start-3 overflow-y-auto overflow-x-hidden sm:col-span-2 md:col-span-3 lg:col-span-4 xl:col-span-5 row-span-11 bg-white rounded-lg shadow-md">
              {children}
            </div>
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
